server.port=8081

logging.level.ru.nesterov=DEBUG

bot.username=revenue analyzer bot
bot.api-token=

bot.secret-token=secret-token
bot.menu-buttons-per-line=2
revenue.analyzer.integration.url=http://localhost:8080