spring.profiles.active=local

server.port=8081

logging.level.ru.nesterov=DEBUG

bot.username=revenue analyzer bot
bot.api-token=

bot.secret-token=secret-token
bot.menu-buttons-per-line=2
bot.control-buttons-auto-update-enabled=false
bot.control-buttons-update-interval-hours=24

revenue.analyzer.integration.url=http://localhost:8080
revenue.analyzer.integration.get-income-analysis-for-month-url=/revenue-analyzer/events/analyzer/getIncomeAnalysisForMonth
revenue.analyzer.integration.get-client-statistic-url=/revenue-analyzer/events/analyzer/getClientStatistic
revenue.analyzer.integration.get-year-busyness-statistics-url=/revenue-analyzer/user/analyzer/getYearBusynessStatistics
revenue.analyzer.integration.generate-recommendation-url=/revenue-analyzer/ai/generateRecommendation
revenue.analyzer.integration.get-user-by-username-url=/revenue-analyzer/user/getUserByUsername
revenue.analyzer.integration.client-create-url=/revenue-analyzer/client/create
revenue.analyzer.integration.create-user-url=/revenue-analyzer/user/createUser
revenue.analyzer.integration.get-schedule-url=/revenue-analyzer/client/getSchedule
revenue.analyzer.integration.get-active-clients-url=/revenue-analyzer/client/getActiveClients
revenue.analyzer.integration.events-backup-url=/revenue-analyzer/events/backup
revenue.analyzer.integration.get-unpaid-events-url=/revenue-analyzer/events/analyzer/getUnpaidEvents
revenue.analyzer.integration.client-url=/revenue-analyzer/client
revenue.analyzer.integration.client-update-url=/revenue-analyzer/client/update
revenue.analyzer.integration.get-users-id-by-role-and-source-url=/revenue-analyzer/user/getUsersIdByRoleAndSource


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=your_strong_password